/* Phaser M12 — Level 1 parity scene. */
class GameScene extends Phaser.Scene {
  constructor(){super('GameScene');}
  preload(){ANGELIC_QUEEN_ASSETS.queue(this);this.load.image('necro-queen-level-up','assets/art/portraits/level-up/necro-queen-level-up.png');this.load.on('loaderror',file=>{if(file&&file.key&&(file.key.indexOf('queen-')===0||file.key==='necro-queen-level-up')){this.queenAssetErrors=this.queenAssetErrors||[];this.queenAssetErrors.push(file.key);}});}
  create(){
    const cfg=window.ANGELIC_PHASER_CONFIG;this.config=cfg;this.queenAssetErrors=this.queenAssetErrors||[];this.cursors=this.input.keyboard.createCursorKeys();this.jumpQueued=false;this.touch=new TouchControls(this);
    this.fireKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Z);this.chargeKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.X);this.lanceKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.C);this.mantleKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.V);this.gravefallKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.B);
    this.levelOneKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ONE);this.levelTwoKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.TWO);this.resetKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.R);this.openingKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.O);this.preludeKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.P);this.aftermathKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.A);
    this.menuKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.I);this.menu1Key=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ONE);this.menu2Key=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.TWO);this.menu3Key=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.THREE);this.closeMenuKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ESC);this.vendorKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.V);
    this.cameras.main.setBackgroundColor('#0b0611');this.cameras.main.setBounds(0,0,cfg.worldWidth,cfg.height);this.world=new FirstTombWorld(this);this.createQueenFallbackTexture();this.createEnemyFallbackTextures();ANGELIC_QUEEN_ASSETS.defineAnimations(this);const initialTexture=this.textures.exists('queen-idle')?'queen-idle':'queen-fallback';
    this.queen=new NecroQueen(this,240,cfg.ground,initialTexture);this.physics.add.collider(this.queen,this.world.groundBody);this.queen.setAnimationState();this.fx=new ANGELIC_FX(this);this.progression=new ProgressionSystem(this,this.queen);this.combat=new CombatSystem(this,this.queen);this.pickups=new PickupSystem(this,this.combat);this.spells=new SpellSystem(this,this.queen,this.combat);this.waves=new WaveSystem(this,this.combat);this.audit=new RuntimeAudit(this);this.narrative=new NarrativeDirector(this);this.menu=new Level1Menu(this,this.progression,this.queen);
    this.banner=this.add.text(cfg.width/2,72,'',{fontFamily:'Georgia,serif',fontSize:'24px',color:'#e7d8f2',stroke:'#0b0611',strokeThickness:7}).setOrigin(.5).setScrollFactor(0).setAlpha(0).setDepth(200);this.bannerT=0;this.bossTitle=this.add.text(cfg.width/2,170,'',{fontFamily:'Georgia,serif',fontStyle:'bold',fontSize:'34px',color:'#d8a94e',stroke:'#0b0611',strokeThickness:10}).setOrigin(.5).setScrollFactor(0).setAlpha(0).setDepth(210);this.bossTitleSub=this.add.text(cfg.width/2,212,'',{fontFamily:'Georgia,serif',fontSize:'14px',color:'#e7d8f2',stroke:'#0b0611',strokeThickness:5}).setOrigin(.5).setScrollFactor(0).setDepth(210);
    this.completeShade=this.add.rectangle(cfg.width/2,cfg.height/2,cfg.width,cfg.height,0x05030a,.82).setScrollFactor(0).setDepth(520).setVisible(false);this.completePanel=this.add.rectangle(cfg.width/2,cfg.height/2,720,300,0x100a18,.97).setStrokeStyle(2,0xd8a94e,.8).setScrollFactor(0).setDepth(521).setVisible(false);this.completeTitle=this.add.text(cfg.width/2,192,'FIRST TOMB CLEARED',{fontFamily:'Georgia,serif',fontSize:'28px',color:'#d8a94e',stroke:'#05030a',strokeThickness:7}).setOrigin(.5).setScrollFactor(0).setDepth(522).setVisible(false);this.completeBody=this.add.text(cfg.width/2,245,'The Skeletal Lord is broken.\nThe dead have answered their Queen.\n\nPress R to restart the run.',{fontFamily:'monospace',fontSize:'14px',align:'center',color:'#e7d8f2',lineSpacing:10}).setOrigin(.5).setScrollFactor(0).setDepth(522).setVisible(false);
    this.add.text(28,22,'PHASER M12 • LEVEL 1 PARITY',{fontFamily:'monospace',fontSize:'13px',color:'#d8a94e',stroke:'#000',strokeThickness:4}).setScrollFactor(0).setDepth(200);this.status=this.add.text(28,46,'',{fontFamily:'monospace',fontSize:'10px',color:'#8f9ab0',stroke:'#000',strokeThickness:3,lineSpacing:4}).setScrollFactor(0).setDepth(200);this.add.text(cfg.width-28,22,'← → MOVE   SPACE / ↑ JUMP',{fontFamily:'monospace',fontSize:'10px',color:'#b18cff',stroke:'#000',strokeThickness:3}).setOrigin(1,0).setScrollFactor(0).setDepth(200);this.add.text(cfg.width-28,45,'Z BOLT  X CHARGE  C LANCE  V MANTLE  B GRAVEFALL',{fontFamily:'monospace',fontSize:'9px',color:'#7dffc0',stroke:'#000',strokeThickness:3}).setOrigin(1,0).setScrollFactor(0).setDepth(200);this.add.text(cfg.width-28,60,'I INVENTORY  O OPENING  P PRELUDE  A AFTERMATH',{fontFamily:'monospace',fontSize:'8px',color:'#6d5a8f',stroke:'#000',strokeThickness:3}).setOrigin(1,0).setScrollFactor(0).setDepth(200);
    this.onQueenDefeated=()=>this.progression.onQueenDefeated();this.onLevelOneComplete=()=>this.narrative.graveLordDefeat(()=>{this.progression.inventory.signet=1;this.narrative.aftermath(()=>this.menu.openVendor());});this.waves.startNext();this.cameras.main.startFollow(this.queen,true,.08,.08);this.cameras.main.setLerp(.08,.08);this.cameras.main.setDeadzone(240,120);this.time.delayedCall(250,()=>this.narrative.levelOnePrelude(()=>this.showBanner('WAVE 1')));
  }
  clearEnemiesForRespawn(){this.combat.enemies.clear(true,true);this.combat.projectiles.clear(true,true);this.combat.enemyProjectiles.clear(true,true);this.pickups.group.clear(true,true);this.combat.waveKills=0;}
  resetRun(){this.scene.restart();}
  unlockSpell(name){this.spells?.unlock(name);}
  showBanner(text){this.banner.setText(text).setAlpha(1);this.bannerT=1.8;}
  showBossTitle(title){this.bossTitle.setText(title).setAlpha(0).setScale(.82);this.bossTitleSub.setText('LORD OF THE FIRST GRAVE').setAlpha(0);this.fx.bossEntrance(this.queen.x+this.queen.face*220,this.config.ground-40);this.narrative.graveLordConfrontation(()=>{});this.tweens.add({targets:this.bossTitle,alpha:1,scale:1,duration:520,ease:'Back.Out'});this.tweens.add({targets:this.bossTitleSub,alpha:1,duration:460,delay:180});this.time.delayedCall(2200,()=>this.tweens.add({targets:[this.bossTitle,this.bossTitleSub],alpha:0,duration:420}));}
  showLevelOneComplete(){this.progression.state='level-complete';this.progression.syncPhysicsPause();this.completeShade.setVisible(true);this.completePanel.setVisible(true);this.completeTitle.setVisible(true);this.completeBody.setVisible(true);this.fx.sigil(this.queen.x,this.queen.y-45,72,0xd8a94e,1);this.fx.cameraPunch(.008,220);}
  update(time,delta){const cfg=this.config,dt=Math.min(delta,50)/1000;this.audit.update(time);this.narrative.update(delta);this.menu.update();if(this.progression.state==='level-complete'){if(Phaser.Input.Keyboard.JustDown(this.resetKey))this.resetRun();return;}if(this.narrative.active||this.menu.mode)return;this.progression.update();if(this.progression.state!=='playing')return;
    const left=this.cursors.left.isDown||this.touch.hold('left'),right=this.cursors.right.isDown||this.touch.hold('right');this.virtualCursors={left:{isDown:left},right:{isDown:right}};const jump=Phaser.Input.Keyboard.JustDown(this.cursors.up)||Phaser.Input.Keyboard.JustDown(this.cursors.space)||this.touch.justPressed('jump');
    if(Phaser.Input.Keyboard.JustDown(this.menuKey)){this.menu.openInventory();return;}if(Phaser.Input.Keyboard.JustDown(this.openingKey))return this.narrative.opening(()=>{});if(Phaser.Input.Keyboard.JustDown(this.preludeKey))return this.narrative.levelOnePrelude(()=>{});if(Phaser.Input.Keyboard.JustDown(this.aftermathKey))return this.narrative.aftermath(()=>{});
    if(Phaser.Input.Keyboard.JustDown(this.fireKey)||this.touch.justPressed('bolt'))this.combat.beginBasicCast();if(Phaser.Input.Keyboard.JustDown(this.chargeKey))this.combat.startCharge();if(Phaser.Input.Keyboard.JustUp(this.chargeKey))this.combat.releaseCharge();if(Phaser.Input.Keyboard.JustDown(this.lanceKey)||this.touch.justPressed('special'))this.spells.castLance();if(Phaser.Input.Keyboard.JustDown(this.mantleKey))this.spells.activateMantle();if(Phaser.Input.Keyboard.JustDown(this.gravefallKey))this.spells.castGravefall();
    this.queen.updateControl(this.virtualCursors,jump,dt);this.queen.setAnimationState();this.combat.update(delta);this.spells.update(delta);this.waves.update(delta);this.world.update(time,delta);this.fx.update(delta);const lookAhead=this.queen.face*120,targetX=Phaser.Math.Clamp(this.queen.x+lookAhead,cfg.width/2,cfg.worldWidth-cfg.width/2),camX=this.cameras.main.midPoint.x;this.cameras.main.scrollX+=(targetX-camX)*.08;
    if(this.bannerT>0){this.bannerT=Math.max(0,this.bannerT-dt);this.banner.setAlpha(this.bannerT<.45?this.bannerT/.45:1);}const installed=ANGELIC_QUEEN_ASSETS.installed(this),installedLabel=installed.length?installed.map(k=>k.replace('queen-','')).join(', '):'fallback';const charge=this.combat.charging?` CHARGE ${this.combat.chargeTime.toFixed(2)}s`:'';const shield=this.queen.shield>0?' SHIELDED':'';this.status.setText(`HP ${Math.ceil(this.queen.hp)}/${this.queen.maxHp}  MANA ${Math.floor(this.queen.mana)}/${this.queen.maxMana}  LV ${this.progression.level}  XP ${Math.floor(this.progression.xp)}/${this.progression.xpNeed}\nWAVE ${this.waves.wave}  FOES ${this.combat.enemies.countActive(true)}  KILLS ${this.combat.totalKills}  GOLD ${this.progression.inventory.gold}${charge}${shield}  loaded:${installedLabel}`);
  }
  createQueenFallbackTexture(){if(this.textures.exists('queen-fallback'))return;const g=this.add.graphics();g.fillStyle(0x8f93a1,1).fillCircle(32,25,22);g.fillStyle(0x131019,1).fillRect(15,43,34,30);g.fillStyle(0xd8d6dc,1).fillRect(24,37,16,8);g.fillStyle(0x5cff9f,1).fillRect(26,28,4,3).fillRect(35,28,4,3);g.fillStyle(0x28232d,1).fillTriangle(19,7,32,0,45,7);g.fillStyle(0xb98cff,1).fillRect(30,3,4,4);g.fillStyle(0xe8e6d4,1).fillRect(24,70,7,18).fillRect(34,70,7,18);g.fillStyle(0x241239,1).fillTriangle(17,70,25,94,8,96).fillTriangle(47,70,39,94,56,96);g.generateTexture('queen-fallback',64,96);g.destroy();}
  createEnemyFallbackTextures(){const make=(key,w,h,fn)=>{if(this.textures.exists(key))return;const g=this.add.graphics();fn(g);g.generateTexture(key,w,h);g.destroy();};make('knight-fallback',45,68,g=>{g.fillStyle(0x4b4e56,1).fillRect(8,10,28,38);g.fillStyle(0x8b909b,1).fillRect(10,7,24,14);g.fillStyle(0x1a1720,1).fillRect(13,13,18,5);g.fillStyle(0x66563b,1).fillRect(12,22,20,4);g.fillStyle(0x2e2731,1).fillRect(12,48,8,18).fillRect(24,48,8,18);g.fillStyle(0xc3bca7,1).fillRect(34,22,3,32);});make('zombie-fallback',44,74,g=>{g.fillStyle(0x495040,1).fillCircle(22,16,12);g.fillRect(10,28,24,34);g.fillStyle(0x9aa28b,1).fillRect(15,14,4,3).fillRect(26,14,4,3);g.fillStyle(0x242025,1).fillRect(13,56,7,16).fillRect(25,56,7,16);});make('cultist-fallback',44,72,g=>{g.fillStyle(0x25182e,1).fillTriangle(22,6,4,36,40,36);g.fillStyle(0xd4c7d9,1).fillCircle(22,18,8);g.fillStyle(0x8d5cf6,1).fillRect(34,30,5,5);g.fillStyle(0x18111f,1).fillRect(14,36,7,30).fillRect(23,36,7,30);});make('mage-fallback',46,76,g=>{g.fillStyle(0x3c2b66,1).fillTriangle(23,4,5,38,41,38);g.fillStyle(0xe1d8e8,1).fillCircle(23,20,8);g.fillStyle(0xb18cff,1).fillCircle(36,34,5);g.fillStyle(0x20162d,1).fillRect(14,37,8,34).fillRect(25,37,8,34);});make('bat-fallback',48,28,g=>{g.fillStyle(0x241b31,1).fillTriangle(4,6,22,14,4,24);g.fillTriangle(44,6,26,14,44,24);g.fillStyle(0x6d5a8f,1).fillCircle(24,14,7);});make('mara-fallback',46,76,g=>{g.fillStyle(0x5a4a43,1).fillCircle(23,13,9);g.fillStyle(0x28212a,1).fillRect(10,23,26,36);g.fillStyle(0xd8c1b0,1).fillRect(15,59,7,15).fillRect(26,59,7,15);g.fillStyle(0xb18cff,1).fillRect(34,25,3,28);});make('grave-lord-fallback',84,132,g=>{g.fillStyle(0x322b35,1).fillCircle(42,25,21);g.fillStyle(0x625a63,1).fillRect(18,42,48,58);g.fillStyle(0x151219,1).fillRect(27,52,30,8);g.fillStyle(0xa42c46,1).fillRect(30,22,6,5).fillRect(49,22,6,5);g.fillStyle(0x9b7a55,1).fillRect(8,55,10,52);g.fillRect(66,55,10,52);g.fillStyle(0x151219,1).fillRect(22,98,14,28).fillRect(48,98,14,28);});}
}
